#!/bin/bash

# reset all submodules and clean them
git submodule foreach --quiet 'echo $name: [$(git reset --hard | awk "{print \$5, \$6}")]'
git submodule foreach --quiet git clean -df
git reset --hard
git clean -df
