#!/usr/bin/env sh
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config auto_balance                 on

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8 
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

# Spaces settings
yabai -m space 1 --label dev
yabai -m space 2 --label music --layout float 
yabai -m space 3 --label chat  --layout float 
yabai -m space 4 --label other --layout float 

# floating app
yabai -m rule --add app="Dash" space=^1 grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="^Font Book$" space=^1 grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="NeteaseMusic" space=^2
yabai -m rule --add app="QQ" space=^3
yabai -m rule --add app="WeChat" space=^3
yabai -m rule --add app="^System Preferences$" space=^4
yabai -m rule --add app="^Tecent Lemon$" space=^4
yabai -m rule --add app="Finder" grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="^Android Studio$" manage=off
