#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# Status bar
yabai -m config external_bar all:20:0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config auto_balance                 on

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float

yabai -m config window_border                on 
yabai -m config window_border_width          4

yabai -m config normal_window_border_color   0xFF1B222D
yabai -m config active_window_border_color   0xFF2B354B


# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  18
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   6


# Spaces settings 
yabai -m space 1 --label "[1] Term"
yabai -m space 2 --label "[2] Web"
yabai -m space 3 --label "[3] Music & Chat"
yabai -m space 4 --label "[4] Dev"
yabai -m space 5 --label "[5] Other" --layout float


# floating app
yabai -m rule --add app="Dash" grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="^Font Book$" space=^5 grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="NeteaseMusic" space=^2 manage=off
yabai -m rule --add app="QQ" space=^3 manage=off
yabai -m rule --add app="WeChat" space=^3 manage=off
yabai -m rule --add app="^System Preferences$" space=^5 manage=off
yabai -m rule --add app="^Tecent Lemon$" space=^5 manage=off
yabai -m rule --add app="Finder" grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="^Android Studio$" space=^4 manage=off
yabai -m rule --add app="Processing" manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^Google Chrome$" space=2


# # Refresh spaces widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on display focus change
# yabai -m signal --add event=display_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh spaces widget on window resize
# yabai -m signal --add event=window_resized action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
# # Refresh process widget on space change
# yabai -m signal --add event=space_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=window_focused action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when focused application changes
# yabai -m signal --add event=application_front_switched action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
# # Refresh spaces widget on when an application window is closed
# yabai -m signal --add event=window_destroyed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"

# # Refresh process widget when current window title changes
# yabai -m signal --add event=window_title_changed action="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"simple-bar-process-jsx\"'"
