#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# Status bar
# yabai -m config external_bar all:20:0

# global settings yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config auto_balance                 on

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float

yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config normal_window_border_color   0XFF232136
yabai -m config active_window_border_color   0XFF3F3C53

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0


# Spaces settings 
yabai -m space 1 --label "[1] Term"
yabai -m space 2 --label "[2] Web"
yabai -m space 3 --label "[3] Work"
yabai -m space 4 --label "[4] Dev"
yabai -m space 5 --label "[5] Music & Chat"


# floating app
yabai -m rule --add app="^Google Chrome$"

yabai -m rule --add app="Finder" grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="^Font Book$" grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="^Digital Color Meter$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

yabai -m rule --add app="Dash" grid=11:7:1:1:5:9 manage=off
yabai -m rule --add app="Processing" manage=off
yabai -m rule --add app="MacZip" manage=off

yabai -m rule --add app="QQ" space=^5 manage=off
yabai -m rule --add app="WeChat" space=^5 manage=off
