#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config focus_follows_mouse          off
yabai -m config auto_balance                 off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float

yabai -m config window_border                off
# yabai -m config window_border_width          8
# yabai -m config normal_window_border_color   0XFF232136
# yabai -m config active_window_border_color   0XFF232136

yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

yabai -m rule --add app="Digital Color Meter" manage=off
yabai -m rule --add app="Android Studio" manage=off
