source $HOME/.config/nvim/plugins/plugins.vim
source $HOME/.config/nvim/modules/general.vim
source $HOME/.config/nvim/modules/keymapping.vim
source $HOME/.config/nvim/modules/alacritty.vim
source $HOME/.config/nvim/modules/coc.vim
source $HOME/.config/nvim/modules/treesitter.vim
source $HOME/.config/nvim/modules/kommentary.vim
source $HOME/.config/nvim/modules/airline.vim
source $HOME/.config/nvim/modules/nvim-tree.vim
source $HOME/.config/nvim/themes/nord.vim
